CREATE TABLE players (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE finished_matches (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         firstPlayer INT NOT NULL,
                         secondPlayer INT NOT NULL,
                         winner  INT NOT NULL,

                         CONSTRAINT fk_finished_matches_player1 FOREIGN KEY (firstPlayer) REFERENCES players(id),
                         CONSTRAINT fk_finished_matches_player2 FOREIGN KEY (secondPlayer) REFERENCES players(id),
                         CONSTRAINT fk_finished_matches_winner  FOREIGN KEY (winner)  REFERENCES players(id),

                         CONSTRAINT chk_finished_matches_players_distinct CHECK (firstPlayer <> secondPlayer),
                         CONSTRAINT chk_finished_matches_winner_is_player  CHECK (winner = firstPlayer OR winner = secondPlayer)
);

CREATE INDEX idx_finished_matches_player1 ON finished_matches(firstPlayer);
CREATE INDEX idx_finished_matches_player2 ON finished_matches(secondPlayer);