INSERT INTO players(name) VALUES ('Nadya');
INSERT INTO players(name) VALUES ('Dmitry');
INSERT INTO players(name) VALUES ('Fedor');
INSERT INTO players(name) VALUES ('Alex');
INSERT INTO players(name) VALUES ('Maria');
INSERT INTO players(name) VALUES ('Ivan');
INSERT INTO players(name) VALUES ('Olga');
INSERT INTO players(name) VALUES ('Sergey');
INSERT INTO players(name) VALUES ('Anna');
INSERT INTO players(name) VALUES ('Pavel');
INSERT INTO players(name) VALUES ('Kirill');
INSERT INTO players(name) VALUES ('Elena');
INSERT INTO players(name) VALUES ('Denis');

INSERT INTO finished_matches(player1, player2, winner) VALUES (1, 2, 2);
INSERT INTO finished_matches(player1, player2, winner) VALUES (3, 1, 1);
INSERT INTO finished_matches(player1, player2, winner) VALUES (2, 3, 3);
INSERT INTO finished_matches(player1, player2, winner) VALUES (1, 4, 4);
INSERT INTO finished_matches(player1, player2, winner) VALUES (2, 5, 2);
INSERT INTO finished_matches(player1, player2, winner) VALUES (3, 6, 6);
INSERT INTO finished_matches(player1, player2, winner) VALUES (7, 1, 7);
INSERT INTO finished_matches(player1, player2, winner) VALUES (8, 2, 8);
INSERT INTO finished_matches(player1, player2, winner) VALUES (9, 3, 3);
INSERT INTO finished_matches(player1, player2, winner) VALUES (10, 4, 10);

INSERT INTO finished_matches(player1, player2, winner) VALUES (11, 5, 5);
INSERT INTO finished_matches(player1, player2, winner) VALUES (12, 6, 12);
INSERT INTO finished_matches(player1, player2, winner) VALUES (13, 7, 7);
INSERT INTO finished_matches(player1, player2, winner) VALUES (1, 5, 1);
INSERT INTO finished_matches(player1, player2, winner) VALUES (2, 6, 2);
INSERT INTO finished_matches(player1, player2, winner) VALUES (3, 7, 3);
INSERT INTO finished_matches(player1, player2, winner) VALUES (4, 8, 8);
INSERT INTO finished_matches(player1, player2, winner) VALUES (5, 9, 9);
INSERT INTO finished_matches(player1, player2, winner) VALUES (6, 10, 6);
INSERT INTO finished_matches(player1, player2, winner) VALUES (7, 11, 11);

INSERT INTO finished_matches(player1, player2, winner) VALUES (8, 12, 8);
INSERT INTO finished_matches(player1, player2, winner) VALUES (9, 13, 13);
INSERT INTO finished_matches(player1, player2, winner) VALUES (10, 1, 1);
INSERT INTO finished_matches(player1, player2, winner) VALUES (11, 2, 11);
INSERT INTO finished_matches(player1, player2, winner) VALUES (12, 3, 12);
INSERT INTO finished_matches(player1, player2, winner) VALUES (13, 4, 4);
INSERT INTO finished_matches(player1, player2, winner) VALUES (5, 10, 10);
INSERT INTO finished_matches(player1, player2, winner) VALUES (6, 11, 6);
INSERT INTO finished_matches(player1, player2, winner) VALUES (7, 12, 12);
INSERT INTO finished_matches(player1, player2, winner) VALUES (8, 13, 8);

INSERT INTO finished_matches(player1, player2, winner) VALUES (9, 1, 9);
INSERT INTO finished_matches(player1, player2, winner) VALUES (10, 2, 2);
INSERT INTO finished_matches(player1, player2, winner) VALUES (11, 3, 11);
INSERT INTO finished_matches(player1, player2, winner) VALUES (12, 4, 12);
INSERT INTO finished_matches(player1, player2, winner) VALUES (13, 5, 5);
INSERT INTO finished_matches(player1, player2, winner) VALUES (1, 6, 1);
INSERT INTO finished_matches(player1, player2, winner) VALUES (2, 7, 7);
INSERT INTO finished_matches(player1, player2, winner) VALUES (3, 8, 3);
INSERT INTO finished_matches(player1, player2, winner) VALUES (4, 9, 4);
INSERT INTO finished_matches(player1, player2, winner) VALUES (5, 12, 12);

INSERT INTO finished_matches(player1, player2, winner) VALUES (6, 13, 13);
INSERT INTO finished_matches(player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO finished_matches(player1, player2, winner) VALUES (10, 11, 10);